---
- name: restart wazuh-agent
  service: 
    name: wazuh-agent
    state: restarted 

- name: restart postfix
  service: 
    name: postfix
    state: restarted 

- name: init aide
  command: aide --init

- name: update grub
  command: grub2-mkconfig –o /boot/grub2/grub.cfg

- name: restart sshd
  systemd:
    name: sshd
    state: restarted
  notify: restart wazuh-agent